### ISSUE TITLE
SSE

### ISSUE THREAD

**Issue by vhirtham** [vhirtham/GDL#27]
- Create helper functions to create masks for shuffle intrinsics etc

### ToDo
- [x] Put all sse related stuff into `base/sse`
- [x] Remove SSE from function names and put them into namespace sse
- [x] move all function that do not generalize a sse intrinsic to own header and rename sse.h to intrinsics.h
- [x] Create function to get a single element -> https://www.reddit.com/r/cpp/comments/7qj001/extract_elements_from_m128/
- [x] Create function to write to a single element
- [x] Create mask function for shuffle
- [x] Replace explicit shuffle masks in Transpose header
- [x] Create mask function for blend
- [x] Replace explicit blend masks in Transpose header
- [x] Create mask function for permute functions
- [x] Replace permute explicit masks in Transpose header
- [x] Think about removing 512bit register support, since I can not test it.
- [x] Replace (+rename) `SSEGetNumRegisterEntries` with `numRegisterValues` template constant (like alignmentBytes)

### Tests
- [x] Test single element getter
- [x] Test single element setter
- [x] Test shuffle masks
- [x] Test blend masks
- [x] Test permute masks

**Comment by vhirtham** [comment]
Finished with commit de1b14abebbb23057693d46829747ebe49d262a7
