### ISSUE TITLE
List of general Optimizations and Fixes

### ISSUE THREAD

**Issue by vhirtham** [vhirtham/GDL#41]
**Better Benchmarks**
Write Python scripts that can create result files for all Benchmarks (Maybe make a result file repository on Github). Store processor data (type, frequency) in the result file name. 
Data should also have a time component to compare different code versions. Time components should also get a tag to describe what has changed. Also adjust the benchmarks for matrices and solvers in a way, that the tested sizes can be changed at compile-time (size steps, minimal size/offset). This makes it possible to benchmark all sizes using python by compiling and running the same benchmark multiple times with different setups.

**`_mm256_permute4x64_pd` and `_mm256_permutevar8x32_ps`**
They perform complete permutations across lanes. Create a Corresponding ´Permute´ template functions. Check the code for every `_mm256_permute2f128_pd` /`_mm256_permute2f128_ps` or `Permute2F128`. If it is followed by an "in lane" permutation, the code might be optimized with the new function
*Update:* They have a control register instead of a U8. The initialization of this register is expensive. It doesn't make sense to use these functions most of the time. The only use case might be if the control register is the result of a calculation. For static permutations, the overhead is too big-

**CMake flags for SSE version and CMake compiler setup**
The compiler setup should be added to each library, executable separately and not globally as it is at the moment. Add a variable for different compiler flags ("architecture/SSE, Warning level") and maybe create some CMake options to select them. Add a Travis test case for SSE (no AVX) setup.

**Use new Transpose function in SSE Matrix class**
FINISH BENCHMARK TODO FIRST to see the effect. The old version was written when only 2x2, 4x4 and 8x8 transpose functions were implemented.

**Move GDL containers to `resources/memory`**
They should not be in `base` since they depend on the memory managers

**Optimize GetValue and SetValue (SIMD)**
Use shuffle with `_mm_cvtf32` for getter and `_mm_broadcast_ss?? with blends for setter

**Replace ReinterpretAsIntRegister (SIMD)**
The implementation uses `reinterpret_cast` which is not the correct way for vector types. Add a generalized intrinsic function (`_mm_cast_Epi` or a better name) and use it instead.

**Introduce alias for `std::size_t`**
`U_T` and use it where appropriate

**Benchmark/Use AVX/SSE accelerated `memset`**
Read the answer of "Benjamin" in:
https://stackoverflow.com/questions/9146395/reset-c-int-array-to-zero-the-fastest-way
Benchmark implementations and use it, if it is really faster for current compilers.

**Create extra `x86` directory**
Move every SSE/AVX related code into that folder. Include the corresponding files where necessary. If c++ 20 modules are introduced, every module should probably have its own directory

**Add `[[nodiscard]]` and `noexcept` to functions**
Check all files and add keywords/attributes if possible

**Apply new naming conventions**
Preceding underscores in template names are suboptimal: 
- https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier
- https://wiki.sei.cmu.edu/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier

Use a naming convention similar to PEP8 in Python.
- snake case Variable names: `my_variable_name`
- capital camel case class and type names: `MyClassName`
- template parameter names: `t_my_template_parameter` for parameters that represent a value and `TMyTemplateParameter` for parameters that represent a type.
- class member variables: `m_my_class_member`

Apply these changes when migrating the repository

**Replace boost unit test framework with google test**
Getting the necessary boost libraries (in Windows) has proven to be a little bit annoying in the past. Google test seems to integrate well into CMake projects without the need to install binaries. It also has mocking tools on board.

When migrating the code to the new Repo, rewrite the tests to use google test. 

**Use c++ 20 modules as soon as they are available for all used compilers**
C++ 20 introduces modules. See [this StackOverflow question](https://stackoverflow.com/questions/22693950/what-exactly-are-c-modules). Unfortunately, it is currently not fully implemented. So keep it in mind.  

**Check implementation of Perspective matrix**
It seems like there is an error in the calculation of the tangent. Seems like instead of multiplying by 2 (because of using half of the FOV angle), it was actually divided by 2. See this [GDSE answer](https://gamedev.stackexchange.com/questions/183196/calculating-directional-shadow-map-using-camera-frustum) for further guidance.

**Remove `*.inl` files**
Put all header-only implementations into the main header below the definitions. Do this during the migration of the repository.

**ToDo**
- [ ] Better Benchmarks - Python script for all/most benchmarks
- [ ] Better Benchmarks - Add time component
- [ ] Better Benchmarks - Compile time setup for matrix and solver sizes
- [x] `_mm256_permute4x64_pd` and `_mm256_permutevar8x32_ps`
- [ ] CMake flags for SSE version and cmake compiler setup
- [ ] Use new Transpose function in SSE Matrix class
- [ ] Move GDL containers to `resources/memory`
- [ ] Optimize GetValue and SetValue (SIMD) 
- [x] Replace ReinterpretAsIntRegister (SIMD)
- [x] Introduce alias for `std::size_t`
- [ ] Benchmark/Use AVX/SSE accelerated `memset`
- [ ] Create extra `x86` directory
- [ ] Add `[[nodiscard]]` and `noexcept` to functions
- [ ] Apply new naming conventions
- [ ] Replace boost unit test framework with google test
- [ ] Use c++ 20 modules as soon as they are available for all used compilers
- [ ] Check implementation of Perspective matrix
- [ ] Remove `*.inl` files
