### ISSUE TITLE
OpenGL interface

### ISSUE THREAD

**Issue by vhirtham** [vhirtham/GDL#9]
**Reevaluate all OpenGL Classes**

Old list of tasks in the comment below.

- Function parameters should avoid STL containers
- Move getter, setter and templates to *.inl 
- Implement advanced debugging features (see cookbook)
- Use new exception macros
- Use GDL containers as class internals
- Create helper functions for each class for debugging purposes. This might be static functions or free functions in a separate header. For examble: If one binds a UBO to a binding point, the corresponding debug function queries the bound object of the bindingpoint and compares it with the UBOs handle.

## ToDo

- [x] Write glew wrapper class and remove glew init from `RenderWindowGLUT` - `GLEWController`?
- [x] Write a glut wrapper - `GLUTController`? --> `contextGLUT`
- [x] Put all OpenGL classes into the namespace OpenGL and remove the GL suffix from the filenames
- [x] Update render window class
- [x] Rename renderWindowGL renderWindowGLUT
- [x] Update shader class
- [x] Update program class
- [x] Update buffer object class
- [x] Update uniform buffer object class
- [x] Update vertex array object class
- [x] OpenGL debugging (class?) - have a look into the OpenGL Cookbook
- [ ] Add buffer object with persistent mapped streaming technique (double/triple/etc... buffered). [Here](https://github.com/fenbf/GLSamples/blob/master/src/PersistentMappedBuffer.cpp) is a code example from [this](https://www.bfilipek.com/2015/01/persistent-mapped-buffers-in-opengl.html) blog entry
- [x] Remove uniform buffer object class and put the extra functions into the buffer object class --- storing the binding point is not necessary and also a bad idea since binding another buffer to the same binding point will invalidate the binding of the first buffer. The stored binding point of the first buffer object won't be updated in this case!

## Tests

- [ ] Test uniform block related functions of program class
- [ ] Buffer object SetData(...) with Vector of type U8

**Comment by vhirtham** [comment]
# Old todo list

**Apply changes**
- [ ] Move internal buffer of the uniform buffer object into an own class that references the uniform buffer object (commit 0a567ec1d36da454598142d3d52fc4b71ec928b9). Name might be UniformBufferObjectBuffer ---> ManagedUniformBufferObject (commit cc2a777d3bc8a7621c7f2974dd3e7efe5ec6b21c) ---> Change to template with bool. If true, buffer and additional functionality is provided. Typedef both versions.
- [ ] Add glew class as singleton which initializes glew only once. Replace glew init in the RenderWindow class with a call to the singleton function.

**Implement tools / features**
- [ ] streaming buffer object - like the buffer object class but uses efficient streaming techniques to update the buffer every frame. Have a look into the [wiki](https://github.com/vhirtham/GDL/wiki/Good-reads) for some links. If most of the functionality is the same as in the current buffer object, make it a template and specialize the varying sections. Use typedefs for every specialized case.

**Program class**
- [x] query and store the programs inputs
- [x] query and store the programs uniformVars
- [x] query and store the programs uniform blocks
- [ ] query and store the programs subroutines and the their fitting functions
- [x] handle uniform arrays
- [ ] handle arrays in uniform blocks
- [x] rename mHandle and related functions (Getters) of program objects (uniforms, inputs etc.) to mLocation

**Tests**
- [x] Shader class - Compilation
- [x] Program class - Link Programs
- [x] Program class - Find inputs
- [x] Program class - Find uniforms
- [x] Program class - Find uniform arrays
- [x] Program class - Find uniform blocks and its members
- [ ] Program class - Find arrays in uniform blocks
- [x] Program class - Set uniforms
- [x] Program class - Set uniform arrays
- [ ] Program class - Set members of uniform blocks
- [ ] Program class - Set array members of uniform blocks
